
export const ENGINE = {

  MAX_TRIPS_BEFORE_BREAK: 4,

  BREAK_MINUTES: 15,

  MAX_DETOUR_ADDED_SECONDS: 8 * 60,

  CLUSTER_WINDOW_MINUTES: 20,

  AGING_HALF_LIFE_SECONDS: 300,

  REOPT_THRESHOLD_SECONDS: 120,

  DEFAULT_DEADLINE_MINUTES: 45,

  TICK_MS: Number(process.env.DISPATCH_TICK_MS ?? 5000),
} as const;
